### ISSUE TITLE
마이페이지 리뷰 작성 문제

### ISSUE THREAD

**Issue by JYeonJun** [illdang100/tovalley#118]
마이페이지 리뷰 작성 문제
상황: 마이페이지 지난 일정 리뷰 작성
문제: 이미지 첨부 안됨
- 그러나 F12를 입력해 개발 모드에 들어가면 첨부한 이미지가 보임
  - 이때, 내가 작성한 평점과 리뷰는 보이지 않음

**Comment by yunzung** [comment]
반응형 웹 구현을 위해 리뷰 작성 버튼 위치를 변경하는데, 설정된 특정 웹 사이즈에 버튼의 display를 none 으로 설정해 안 보이게 했던 것이 문제 -> 버튼 위치를 두 개 두는 것이 아니라 하나의 위치를 absolute로 고정하여 리뷰 작성 페이지에 영향이 가지않도록 하였음
