### ISSUE TITLE
계곡 상세페이지 리뷰 페이징 문제

### ISSUE THREAD

**Issue by JYeonJun** [illdang100/tovalley#119]
서버에서 보내는 상세페이지 리뷰 데이터에 정체 모를 데이터 하나가 포함되어 있음
- totalPage는 2가 맞다
- 다음 페이지 리뷰를 가져오지 못한다.
- 이상한 데이터가 하나 포함되어 있다.
<img width="1225" alt="image" src="https://github.com/illdang100/tovalley/assets/97449471/41ab6247-8fce-4b85-ba14-672a82515b99">
<img width="1144" alt="image" src="https://github.com/illdang100/tovalley/assets/97449471/8fa98fb0-1265-4742-8a51-29440e20ccbc">
<img width="604" alt="image" src="https://github.com/illdang100/tovalley/assets/97449471/24a2fac6-050b-438f-9604-96777f11ee45">

**Comment by yunzung** [comment]
- 서버에서 보내주는 리뷰 데이터 수는 5개인데 프론터에서 서버로 10개를 요청함 -> 5개 요청으로 수정
<img width="657" alt="image" src="https://github.com/illdang100/tovalley/assets/80948330/0a8f05eb-95fb-4a5f-bbb0-5b2ad9061dba">
- 서버에서 리뷰 데이터를 다 받아오기 전에 화면이 로드되면 값이 모두 null 로 받아와지기 때문에 에러가 발생함 -> 미리 초기 값을 설정하는데 여기서 실수로 초기 값을 하나 더 넣어서 생긴 문제
<img width="490" alt="image" src="https://github.com/illdang100/tovalley/assets/80948330/8c8bf6d8-569b-4f11-a0e3-22d88d683f93">
