### ISSUE TITLE
커뮤니티 댓글 작성 오류

### ISSUE THREAD

**Issue by JYeonJun** [illdang100/tovalley#205]
"hello"라는 닉네임을 가진 사용자가 "형곡빵빵"의 게시글에 댓글을 작성한 경우, "hello"라는 닉네임으로 댓글이 작성되는 것이 아닌 게시글 작성자인 "형곡빵빵"의 닉네임과 프로필로 작성된다.
![image](https://github.com/illdang100/tovalley/assets/97449471/f14dd8c1-8949-4747-b486-e3c4711d9210)

새로고침을 진행하면, 정상적으로 수정되는 것을 보아 리액트 측 문제로 확인된다.

**Comment by hzxng** [comment]
사용자 ux 를 고려하여 optimistic ui 를 구현하기 위해 서버에 요청을 보내기 전에 댓글이 입력되도록 하였음. 테스트 당시 글 작성 유저와 댓글 작성 유저가 같아 착각해서 구현을 한 것으로 pr 했지만 로그인 한 유저의 닉네임과 프로필 사진 등 정보를 프론트에서 가지고 있지 않아 구현 불가함을 알게 됨. 
댓글 작성 후 서버에서 보내주는 응답 데이터로 댓글 list를 업데이트 하는 방식으로 수정하였음.
